CREATE TABLE Village (
	Village_name VARCHAR(30) PRIMARY KEY,
	Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE Building (
	BuildingID INT AUTO_INCREMENT PRIMARY KEY,
	Village_name VARCHAR(30),
	Building_name VARCHAR(30) NOT NULL,
	Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (Village_name) REFERENCES Village(Village_name)
);

CREATE TABLE Domain (
	DomainID DOUBLE PRIMARY KEY,
	Village_name VARCHAR(30),
	Domain_name VARCHAR(30) NOT NULL,
	Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (Village_name) REFERENCES Village(Village_name)
);

CREATE TABLE House (
	HouseID INT AUTO_INCREMENT PRIMARY KEY,
	DomainID DOUBLE,
	GPS VARCHAR(30),
	Details VARCHAR(100),
	Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (DomainID) REFERENCES Domain(DomainID)
);

CREATE TABLE Person (
	PersonID INT AUTO_INCREMENT PRIMARY KEY,
	HouseID INTEGER,
	Firstname VARCHAR(30) NOT NULL,
	Lastname VARCHAR(30) NOT NULL,
	Birthdate DATE,
	Profession VARCHAR(30),
	Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (HouseID) REFERENCES House(HouseID)
);

CREATE TABLE Multimedia (
	MultimediaID INT AUTO_INCREMENT PRIMARY KEY,
	HouseID INTEGER,
	Picture VARCHAR(255),
	Video VARCHAR(255),
	Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (HouseID) REFERENCES House(HouseID)
);